# Site settings
title: Tarraneh Eftekhari, Radio Astronomer
 baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tarraneheftekhari.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tarraneh Eftekhari
user_description: I am a CIERA Postdoctoral Fellow and Radio Astronomer at Northwestern University and a member of the Fast and Fortunate for FRB Follow-up (F4) collaboration. My research focuses on broad range of astrophysical transients, ranging from fast radiobursts to superluminous supernovae and tidal disruption events. I'm particularly interested in studying the radio properties of these sources to answer key questions about their progenitors, outflows, and environments.
user_title: CIERA Postdoctoral Fellow
email: teftekhari@northwestern.edu
twitter_username: etarraneh
github_username:  etarraneh

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
